name: Trigger auto deployment for rust-rocker-vite-react

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/rust-rocker-vite-react-AutoDeployTrigger-7bbdffaa-f559-45f2-8422-2abe12bab395.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RUSTROCKERVITEREACT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RUSTROCKERVITEREACT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RUSTROCKERVITEREACT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.RUSTROCKERVITEREACT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RUSTROCKERVITEREACT_REGISTRY_PASSWORD }}
          containerAppName: rust-rocker-vite-react
          resourceGroup: serverless
          imageToBuild: giuliohome/rust-rocker-vite-react:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


